name: porviders
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.0.11  # Add version for shared_preferences
  avatar_glow: ^2.0.0  # Ensure version for avatar_glow
  get: ^4.6.5  # Add version for get
  image_picker: ^1.1.2
  loading_more_list: ^7.1.0


  flutter_gen: ^4.1.0
  google_fonts: ^6.2.1
  image_blur: ^1.0.0
  cached_network_image: ^3.2.0
  dio: ^5.7.0
  typing_text_animation: ^0.1.0
  text_transformation_animation: ^0.1.4
  shimmer: ^3.0.0
  animated_toggle_switch: ^0.8.4
  loading_animation_widget: ^1.3.0
  slide_countdown: ^2.0.2
  timeline_tile: ^2.0.0
  scratcher: ^2.5.0
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.2
  photo_view: ^0.15.0
  animated_background: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  flutter_gen_runner: ^4.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
